### ISSUE TITLE
Cannot change state of first command queue

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#365] opened 2019-11-07 22:46 UTC
Environment: YAMCS 4.10.4, Mac OS X 10.14.6, Safari 13.0.2

You can change the state of the first command queue, but only once. To reproduce:

1. Configure at least two queues, all enabled.
2. Start YAMCS.
3. Go to the Commanding > Command Queues screen.

Expected and actual result: First command queue is in ACCEPT state.

4. Click on the three dots to the right of the first queue, and select Change action > Reject.

Expected and actual result: Queue changes state.

5. Click on the three dots to the right of the first queue.

Expected result: The "Change action" popup appears and waits for you to select a new state.

Actual result: the "Change action" popup appears, but then disappears. If you're very fast, you may be able to change the queue state, but I was never successful.

Note: I have reproduced this in Chrome. It does not affect the popup functionality for the other command queues, only the first. Also, as indicated in the steps to reproduce, you can change the state of the first queue one time before the problem occurs. Not sure whether that means the problem is related to the state of the first queue (not ACCEPT, after the change in step 4) or related to the fact that the state was modified once.

**Comment by fqqb** [comment] 2019-11-07 23:23
The blink effect is only a CSS animation though.
I can only try later, but I suspect that maybe the queue where you are observing this, is getting updated for some other reason (for example because commands are going through it).

A bug nonetheless, i'll try to reproduce and fix soon.

**Comment by merose** [comment] 2019-11-07 23:50
No, this was when no commands were being sent. But you're right, it's unrelated to the HOLD state. I'll update the description. It only affects the first queue in the list.

**Comment by fqqb** [comment] 2019-11-08 11:31
Can it be that you are using the property "stateExpirationTimeS" on that queue's configuration? I was able to reproduce your description, but only when using this property.

When changing a queue's action, the use of this property causes 1 hz updates on the live data connection (with progress indication). These were causing the row for that queue to be re-rendered (thereby closing the popup).

This behaviour is fixed, as part of pr #366

**Comment by merose** [comment] 2019-11-08 17:03
Yes, I had copied this from etc/command-queue.yaml.sample, but edited it to change to use "minLevel" to avoid the new warning, and moved it to be the first queue.

    ops-critic:
      state: enabled
      minLevel: watch
      stateExpirationTimeS: 300

I don't need an expiration time, so I'll remove it, for now. Thanks for the fix!

**Closed** 2019-11-12 01:25 UTC
